###############################
#    Omikuzi plugin Config
#    Developed by yamagami2211
###############################

# エフェクトの時間 [int(数字のみ)]
# 秒数をプラグイン側でTickに計算します。
EffectTime: 90

# エフェクトのレベル [int(数字のみ)]
#本来のレベルは数字+1です。例えば 1 の場合、レベルは 2 になります。
EffectLevel: 4
